<?php

namespace app\config;


use PDO;

/**
 * Class MySQL
 * @package app\config
 */
class MySQL extends Database implements ActionsDatabase
{

    /**
     * Setter method of the database.
     * @param string $servername is name server of the mysql to the database.
     */
    public function setServername(string $servername): void
    {
        parent::setServername($servername); // TODO: Change the autogenerated stub
    }

    /**
     * Getter method of the database.
     * @return string $Username is name server of the mysql to the database.
     */
    public function getUsername(): string
    {
        return parent::getUsername(); // TODO: Change the autogenerated stub
    }

    /**
     * Setter method of the database.
     * @param string $username is name server of the mysql to database.
     */
    public function setUsername(string $username): void
    {
        parent::setUsername($username); // TODO: Change the autogenerated stub
    }

    /**
     * Getter method of the database.
     * @return string $password is password server of the mysql to database.
     */
    public function getPassword(): string
    {
        return parent::getPassword(); // TODO: Change the autogenerated stub
    }

    /**
     * Setter method of the database.
     * @param string $password is password server of the mysql to database.
     */
    public function setPassword(string $password): void
    {
        parent::setPassword($password); // TODO: Change the autogenerated stub
    }

    /**
     * MySQL constructor three parameter.
     * @param string $servername is name of the Server MySql.
     * @param string $username is name of the database MySql.
     * @param string $password is password of the database Mysql.
     */
    public function __construct(string $servername, string $username, string $password)
    {
        $this->setServername($servername);
        $this->setUsername($username);
        $this->setPassword($password);

        $this->connection();
    }

    /**
     * A method connect database of the MySQL call by __construct.
     */
    public function connection()
    {
        // TODO: Implement connection() method.
        try {
            $conn = new PDO($this->servername,
                $this->username,
                $this->password);

            // set the PDO error mode to exception
            $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            echo "Connected successfully";
        } catch (\PDOException $exception) {
            echo $exception->getMessage();
        }
    }

    public function get()
    {
        // TODO: Implement get() method.
    }

    public function create()
    {
        // TODO: Implement create() method.
    }

    public function update()
    {
        // TODO: Implement update() method.
    }

    public function remove()
    {
        // TODO: Implement remove() method.
    }
}